### ISSUE TITLE
Erro na extensão SEI+TRELLO

### ISSUE THREAD

**Issue by daaldpe** [luiscrjunior/sei-trello#65] opened 2023-05-15 13:34 UTC
a extensão apresenta msg de erros e não dá acesso a etiquetas do quadro.
![WhatsApp Image 2023-05-15 at 09 24 11](https://github.com/luiscrjunior/sei-trello/assets/133667110/f78bc80e-4104-486f-a415-179b74b6ac25)
![WhatsApp Image 2023-05-15 at 09 24 44](https://github.com/luiscrjunior/sei-trello/assets/133667110/5b2c3dc0-a271-4e91-b97c-6423c0271041)
![WhatsApp Image 2023-05-15 at 09 25 06](https://github.com/luiscrjunior/sei-trello/assets/133667110/6915bbd1-0764-4de8-9ed8-1e21d5ac90b2)
![image](https://github.com/luiscrjunior/sei-trello/assets/133667110/372c61b1-2729-415c-8185-1eef0b62ebc0)
![image](https://github.com/luiscrjunior/sei-trello/assets/133667110/31d52e84-d0f0-4d88-a226-7e298124aa74)

**Comment by luiscrjunior** [comment] 2024-09-10 14:21
Duplicate of #57

**Closed by luiscrjunior** 2024-09-10 14:21 UTC
